import { Trash2 } from 'lucide-react';
import { FieldHelp, PanelTitle } from '../DisplayPrimitives';
import type { WorkflowEdge, WorkflowNode } from '../../types';

export type EdgeConfigProps = { edge?: WorkflowEdge; nodes: WorkflowNode[]; onChange: (patch: Partial<WorkflowEdge>) => void; onDelete: () => void };
export function EdgeConfig({ edge, nodes, onChange, onDelete }: EdgeConfigProps) {
  if (!edge) return <div className="edge-config-empty"><PanelTitle title="边配置" /><p className="empty-text">点击画布连线后配置条件分支。</p></div>;
  return <div className="config-form edge-config"><PanelTitle title="边配置" /><label>source<select value={edge.source} onChange={(event) => onChange({ source: event.target.value })}>{nodes.map((node) => <option key={node.id} value={node.id}>{node.id}</option>)}</select><FieldHelp>分支起点节点，条件会基于这个节点的输出或状态判断。</FieldHelp></label><label>target<select value={edge.target} onChange={(event) => onChange({ target: event.target.value })}>{nodes.map((node) => <option key={node.id} value={node.id}>{node.id}</option>)}</select><FieldHelp>条件命中后要执行的下游节点。</FieldHelp></label><label>condition<select value={edge.condition ?? 'always'} onChange={(event) => onChange({ condition: event.target.value })}><option value="always">always</option><option value="contains">contains</option><option value="on_status">on_status</option><option value="truthy_output">truthy_output</option></select><FieldHelp>always 总是执行；contains 检查输出文本；on_status 检查节点状态；truthy_output 检查字段是否有值。</FieldHelp></label><label>value<input value={edge.value ?? ''} onChange={(event) => onChange({ value: event.target.value })} /><FieldHelp>条件匹配值，例如 contains 要包含的关键词，或 on_status 的 completed/failed。</FieldHelp></label><label>source_path<input value={edge.source_path ?? ''} placeholder="report_markdown / status / results.0.content" onChange={(event) => onChange({ source_path: event.target.value })} /><FieldHelp>可选，从源节点输出中取指定字段再判断；为空时判断整个输出。</FieldHelp></label><button className="danger" onClick={onDelete}><Trash2 size={15} />删除连线</button></div>;
}
