import { ArrowRight } from 'lucide-react';
import type { PointerEvent, Ref } from 'react';
import type { NodeStatus, WorkflowEdge, WorkflowNode } from '../../types';

export type WorkflowCanvasProps = { canvasRef: Ref<HTMLDivElement>; canvasSize: { width: number; height: number }; connectFrom: string | null; edges: WorkflowEdge[]; nodes: WorkflowNode[]; nodeStatus: Record<string, NodeStatus>; selectedEdgeKey: string; selectedNodeId: string; onCanvasPointerMove: (event: PointerEvent<HTMLDivElement>) => void; onDrop: (event: React.DragEvent<HTMLDivElement>) => void; onEndPointer: () => void; onStartCanvasPan: (event: PointerEvent<HTMLDivElement>) => void; onStartMove: (event: PointerEvent<HTMLDivElement>, node: WorkflowNode) => void; onSelectEdge: (edge: WorkflowEdge) => void; onToggleConnect: (nodeId: string) => void; };
const edgeKey = (edge: WorkflowEdge) => `${edge.source}:${edge.target}:${edge.condition ?? 'always'}:${edge.value ?? ''}:${edge.source_path ?? ''}`;

export function WorkflowCanvas({ canvasRef, canvasSize, connectFrom, edges, nodes, nodeStatus, selectedEdgeKey, selectedNodeId, onCanvasPointerMove, onDrop, onEndPointer, onStartCanvasPan, onStartMove, onSelectEdge, onToggleConnect }: WorkflowCanvasProps) {
  return <div ref={canvasRef} className="workflow-canvas" onDragOver={(event) => event.preventDefault()} onDrop={onDrop} onPointerDown={onStartCanvasPan} onPointerMove={onCanvasPointerMove} onPointerUp={onEndPointer} onPointerCancel={onEndPointer}><div className="canvas-surface" style={{ width: canvasSize.width, height: canvasSize.height }}><svg className="edges">{edges.map((edge) => { const source = nodes.find((node) => node.id === edge.source); const target = nodes.find((node) => node.id === edge.target); if (!source || !target) return null; const x1 = source.x + 164; const y1 = source.y + 31; const x2 = target.x; const y2 = target.y + 31; const key = edgeKey(edge); const label = edge.condition && edge.condition !== 'always' ? edge.condition : ''; return <g key={key} className={selectedEdgeKey === key ? 'selected-edge' : ''} onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); onSelectEdge(edge); }}><path d={`M ${x1} ${y1} C ${x1 + 58} ${y1}, ${x2 - 58} ${y2}, ${x2} ${y2}`} /><circle cx={x2} cy={y2} r="3" />{label ? <text x={(x1 + x2) / 2 - 24} y={(y1 + y2) / 2 - 8}>{label}</text> : null}</g>; })}</svg>{nodes.map((node) => <div key={node.id} className={`flow-node ${connectFrom === node.id ? 'connecting' : ''} ${selectedNodeId === node.id ? 'selected' : ''} ${nodeStatus[node.id]}`} style={{ transform: `translate(${node.x}px, ${node.y}px)` }} onPointerDown={(event) => onStartMove(event, node)}><button className="connector" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); onToggleConnect(node.id); }} title="连接节点"><ArrowRight size={14} /></button><strong>{node.name}</strong><span>{node.type}</span></div>)}</div></div>;
}
