"""Typed persistence contracts and PostgreSQL readiness inventory.

The inventory is executable: the factory refuses PostgreSQL until every
domain is implemented and verified. SQLite remains the reference backend.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


class TaskStore(Protocol):
    def create_task(self, task_id: str, goal: str, project_path: str | None, status: str, context: dict[str, Any] | None = None, input_state: dict[str, Any] | None = None) -> dict[str, Any] | None: ...
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    def list_tasks(self, limit: int = 100, offset: int = 0) -> list[dict[str, Any]]: ...
    def claim_next_task(self, worker_id: str, lease_seconds: int = 30) -> dict[str, Any] | None: ...
    def save_task_bundle(self, task_id: str, status: str, final_report: str | None, artifacts: list[tuple[str, str, Any]], events: list[dict[str, Any]], **kwargs: Any) -> None: ...


class WorkflowStore(Protocol):
    def save_workflow(self, workflow_id: str, name: str, description: str, nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> dict[str, Any]: ...
    def list_workflows(self) -> list[dict[str, Any]]: ...
    def get_workflow(self, workflow_id: str) -> dict[str, Any] | None: ...


class ReviewStore(Protocol):
    def record_review_action(self, task_id: str, action: str, comment: str | None = None) -> dict[str, Any]: ...
    def apply_review_transition(self, task_id: str, action: str, comment: str | None, status: str, events: list[dict[str, Any]], **kwargs: Any) -> dict[str, Any] | None: ...


class SkillStore(Protocol):
    def list_skills(self, category: str | None = None) -> list[dict[str, Any]]: ...
    def get_skill(self, skill_code: str) -> dict[str, Any] | None: ...
    def save_skill_execution_log(self, log: dict[str, Any]) -> dict[str, Any]: ...


class McpStore(Protocol):
    def list_mcp_servers(self) -> list[dict[str, Any]]: ...
    def save_mcp_server(self, server: dict[str, Any]) -> dict[str, Any]: ...
    def list_mcp_tools(self, server_id: str | None = None) -> list[dict[str, Any]]: ...


class MarketplaceStore(Protocol):
    def save_marketplace_install(self, record: dict[str, Any]) -> dict[str, Any]: ...
    def list_marketplace_installs(self, limit: int = 80, package_type: str | None = None) -> list[dict[str, Any]]: ...


class AuditStore(Protocol):
    def save_security_audit(self, record: dict[str, Any]) -> dict[str, Any]: ...
    def list_security_audits(self, limit: int = 100, actor_id: str | None = None, role: str | None = None, action: str | None = None, status: str | None = None) -> list[dict[str, Any]]: ...


class MemoryStore(Protocol):
    def extract_candidates(self, content: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    def list_memories(self, **kwargs: Any) -> list[dict[str, Any]]: ...
    def get_memory(self, memory_id: str) -> dict[str, Any] | None: ...


class LlmStore(Protocol):
    def save_llm_trace(self, trace: dict[str, Any]) -> dict[str, Any]: ...
    def list_llm_traces(self, limit: int = 50, agent: str | None = None) -> list[dict[str, Any]]: ...
    def llm_usage_summary(self, limit: int = 500, agent: str | None = None) -> dict[str, Any]: ...


class PromptStore(Protocol):
    def upsert_prompt_version(self, prompt: dict[str, Any]) -> dict[str, Any]: ...
    def list_prompt_versions(self, agent: str | None = None) -> list[dict[str, Any]]: ...
    def get_prompt_version(self, agent: str, prompt_version: str) -> dict[str, Any] | None: ...


class BenchmarkStore(Protocol):
    def create_benchmark_run(self, run_id: str, name: str, benchmark_type: str, config: dict[str, Any]) -> dict[str, Any]: ...
    def append_benchmark_result(self, result: dict[str, Any]) -> dict[str, Any]: ...
    def finish_benchmark_run(self, run_id: str, status: str, summary: dict[str, Any]) -> dict[str, Any]: ...


class RagStore(Protocol):
    def ingest(self, collection: str, documents: list[dict[str, Any]], chunks: list[dict[str, Any]]) -> dict[str, int]: ...
    def query(self, collection: str, question: str, limit: int = 5, actor_id: str = "local-user") -> list[dict[str, Any]]: ...
    def list_documents(self, collection: str | None = None, actor_id: str = "local-user") -> list[dict[str, Any]]: ...
    def source(self) -> str: ...
    def embed_documents(self, texts: list[str]) -> list[list[float]]: ...
    def embed_query(self, text: str) -> list[float]: ...


@dataclass(frozen=True)
class DomainContract:
    sqlite_tables: tuple[str, ...]
    methods: tuple[str, ...]
    postgres_status: str


DOMAIN_CONTRACTS: dict[str, DomainContract] = {
    "task": DomainContract(("agent_task", "agent_task_event", "agent_task_artifact", "agent_worker"), ("create_task", "update_task", "get_task", "list_tasks", "get_task_by_idempotency_key", "get_task_input", "claim_next_task", "claim_task", "heartbeat_task", "recover_expired_tasks", "recover_expired_task_ids", "cancel_task", "is_task_cancelled", "is_task_failed", "append_event", "get_events", "get_events_after", "save_artifact", "get_artifacts", "save_task_bundle", "queue_task_resume"), "supported"),
    "workflow": DomainContract(("workflow_definition",), ("save_workflow", "list_workflows", "get_workflow"), "supported"),
    "review": DomainContract(("human_review_action", "agent_task", "agent_task_event", "agent_task_artifact"), ("record_review_action", "apply_review_transition"), "supported"),
    "skill": DomainContract(("skill_plugin", "skill_registry", "skill_version_snapshot", "skill_approval", "skill_execution_log"), ("seed_builtin_skills", "list_skill_plugins", "list_skills", "get_skill", "update_skill_enabled", "uninstall_skill_plugin", "set_skill_approval", "get_skill_approval", "list_skill_approvals", "save_skill_execution_log", "list_skill_execution_logs", "list_skill_versions", "rollback_skill_version"), "supported"),
    "mcp": DomainContract(("mcp_server_config", "mcp_tool_registry", "mcp_tool_approval", "mcp_tool_call_log"), ("save_mcp_server", "list_mcp_servers", "get_mcp_server", "update_mcp_server_status", "upsert_mcp_tool", "prune_mcp_tools", "list_mcp_tools", "get_mcp_tool", "update_mcp_tool_enabled", "set_mcp_tool_approval", "get_mcp_tool_approval", "save_mcp_call_log", "list_mcp_call_logs"), "supported"),
    "marketplace": DomainContract(("plugin_marketplace_install", "skill_plugin", "skill_registry"), ("save_marketplace_install", "list_marketplace_installs", "get_latest_marketplace_install", "set_marketplace_approval"), "supported"),
    "audit": DomainContract(("security_audit_log",), ("save_security_audit", "list_security_audits"), "supported"),
    "memory": DomainContract(("memory_record", "memory_lifecycle_event"), ("extract_candidates", "list_memories", "get_memory", "confirm", "reject", "delete", "expire_due_memories", "list_lifecycle_events"), "supported"),
    "llm": DomainContract(("llm_call_trace",), ("save_llm_trace", "list_llm_traces", "llm_usage_summary"), "supported"),
    "prompt": DomainContract(("llm_prompt_version",), ("upsert_prompt_version", "set_active_prompt_version", "get_prompt_version", "list_prompt_versions", "get_active_prompt_version"), "supported"),
    "benchmark": DomainContract(("benchmark_run", "benchmark_result"), ("create_benchmark_run", "append_benchmark_result", "finish_benchmark_run", "list_benchmark_runs", "get_benchmark_run"), "supported"),
    "rag": DomainContract(("rag_document", "rag_chunk", "rag_gold_case"), ("ingest", "query", "list_documents", "set_document_acl", "add_note", "delete_note", "list_gold_cases", "save_gold_case", "delete_gold_case", "status", "source", "embed_documents", "embed_query"), "supported"),
}


def unsupported_postgres_domains() -> dict[str, DomainContract]:
    return {name: contract for name, contract in DOMAIN_CONTRACTS.items() if contract.postgres_status != "supported"}
