import { Activity, BarChart3, Database, FileText, History, Play, RefreshCw, Save, Trash2 } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { FieldHelp, KpiCard, PanelTitle } from '../components/DisplayPrimitives';
import { deleteRagGoldCase, listRagGoldCases, saveRagGoldCase } from '../services/rag';
import type { BenchmarkCase, BenchmarkRun, BenchmarkType, RagGoldCase } from '../types';

type Props = { benchmarkType: BenchmarkType; runs: BenchmarkRun[]; selectedRun: BenchmarkRun | null; running: boolean; error: string; onBenchmarkTypeChange: (type: BenchmarkType) => Promise<void>; onRun: (payload: { name: string; agent_code: string; iterations: number; cases: BenchmarkCase[] }) => Promise<BenchmarkRun>; onOpen: (runId: string) => Promise<void>; onRefresh: () => Promise<void>; };
const types: BenchmarkType[] = ['mcp', 'llm', 'rag', 'workflow', 'collaboration'];

export function BenchmarkPage({ benchmarkType, runs, selectedRun, running, error, onBenchmarkTypeChange, onRun, onOpen, onRefresh }: Props) {
  const [name, setName] = useState(runName(benchmarkType)); const [agentCode, setAgentCode] = useState('benchmark_runner'); const [iterations, setIterations] = useState(3); const [casesText, setCasesText] = useState(JSON.stringify(defaultCases(benchmarkType), null, 2)); const [message, setMessage] = useState('');
  const [goldCases, setGoldCases] = useState<RagGoldCase[]>([]); const [gold, setGold] = useState({ case_id: '', collection: 'default', question: '', expected_chunk_ids: '', expected_paths: '', expected_keywords: '', enabled: true });
  const summary = selectedRun?.summary ?? {}; const results = selectedRun?.results ?? [];
  useEffect(() => { setName(runName(benchmarkType)); setCasesText(JSON.stringify(defaultCases(benchmarkType), null, 2)); setMessage(''); if (benchmarkType === 'rag') refreshGold().catch(() => undefined); }, [benchmarkType]);
  async function refreshGold() { setGoldCases(await listRagGoldCases('', true)); }
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); try { const run = await onRun({ name, agent_code: agentCode, iterations, cases: parse(casesText, []) }); setMessage(`Benchmark completed: ${run.run_id}`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Benchmark failed'); } }
  async function saveGold(event: FormEvent) { event.preventDefault(); const saved = await saveRagGoldCase({ case_id: gold.case_id, collection: gold.collection || 'default', question: gold.question, expected_chunk_ids: lines(gold.expected_chunk_ids), expected_paths: lines(gold.expected_paths), expected_keywords: lines(gold.expected_keywords), enabled: gold.enabled, metadata: { limit: 5, source: 'ui_gold_set' } }); setMessage(`Gold Set saved: ${saved.case_id}`); setGold({ case_id: '', collection: 'default', question: '', expected_chunk_ids: '', expected_paths: '', expected_keywords: '', enabled: true }); await refreshGold(); }
  function useGold() { setCasesText(JSON.stringify(goldCases.filter((item) => item.enabled).map((item) => ({ case_id: item.case_id, tool_name: 'rag.query', arguments: { collection: item.collection, question: item.question, expected_chunk_ids: item.expected_chunk_ids, expected_paths: item.expected_paths, expected_keywords: item.expected_keywords, limit: Number(item.metadata?.limit ?? 5) }, enabled: item.enabled })), null, 2)); }
  return <section className="page-grid benchmark-page">
    <div className="panel benchmark-control"><PanelTitle icon={<BarChart3 size={17} />} title="Benchmark Run" action={<button className="icon-button" onClick={() => onRefresh()}><RefreshCw size={15} /></button>} /><form className="benchmark-form" onSubmit={submit}><div className="benchmark-type-tabs">{types.map((type) => <button key={type} type="button" className={benchmarkType === type ? 'active' : ''} onClick={() => onBenchmarkTypeChange(type)}>{label(type)}</button>)}</div><label>name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>agent_code<input value={agentCode} onChange={(e) => setAgentCode(e.target.value)} /><FieldHelp>默认 benchmark_runner；MCP 评测时必须有对应审批。</FieldHelp></label><label>iterations<input type="number" min={1} max={20} value={iterations} onChange={(e) => setIterations(Number(e.target.value))} /></label><label>cases JSON<textarea value={casesText} onChange={(e) => setCasesText(e.target.value)} /></label><button className="primary" disabled={running}>{running ? <RefreshCw className="spin" size={17} /> : <Play size={17} />}{running ? 'Running...' : `Run ${label(benchmarkType)} Benchmark`}</button>{message ? <p className="benchmark-message">{message}</p> : null}{error ? <p className="error-text">{error}</p> : null}</form></div>
    <div className="panel benchmark-summary"><PanelTitle icon={<Activity size={17} />} title="Metrics" /><div className="benchmark-kpis"><KpiCard label="total" value={String(summary.total ?? 0)} /><KpiCard label="success" value={`${Math.round(Number(summary.success_rate ?? 0) * 100)}%`} /><KpiCard label="p95" value={`${summary.p95_latency_ms ?? 0}ms`} /><KpiCard label="failed" value={String(summary.failed ?? 0)} /></div>{summary.benchmark_focus ? <p className="benchmark-focus">{String(summary.benchmark_focus)}</p> : null}</div>
    <div className="panel benchmark-history"><PanelTitle icon={<History size={17} />} title="History" />{runs.map((run) => <button key={run.run_id} className={selectedRun?.run_id === run.run_id ? 'active' : ''} onClick={() => onOpen(run.run_id)}><strong>{run.name}</strong><span>{run.status} / {run.summary?.total ?? 0} calls / {run.started_at}</span></button>)}{!runs.length ? <p className="empty-text">暂无 Benchmark 历史。</p> : null}</div>
    <div className="panel benchmark-results"><PanelTitle icon={<FileText size={17} />} title="Result Details" action={<span className="small-muted">{selectedRun?.run_id ?? 'no run selected'}</span>} /><div className="benchmark-result-grid">{results.map((item) => <article key={`${item.case_id}-${item.iteration}-${item.id ?? item.created_at}`} className={`benchmark-result-item ${item.status}`}><div className="benchmark-result-head"><strong>{item.case_id}</strong><span>{item.iteration}</span><span>{item.status}</span><span>{item.latency_ms}ms</span></div>{item.error_message ? <p className="benchmark-error">{first(item.error_message)}</p> : null}<details className="mcp-log-details"><summary><span>JSON</span></summary><pre>{JSON.stringify(item, null, 2)}</pre></details></article>)}{!results.length ? <p className="empty-text">选择历史或运行新的 Benchmark 后显示逐次执行明细。</p> : null}</div></div>
    {benchmarkType === 'rag' ? <div className="panel benchmark-gold"><PanelTitle icon={<Database size={17} />} title="RAG Gold Set" action={<button className="icon-button" onClick={() => refreshGold()}><RefreshCw size={15} /></button>} /><div className="rag-gold-layout"><form className="rag-gold-form" onSubmit={saveGold}><label>case_id<input value={gold.case_id} onChange={(e) => setGold({ ...gold, case_id: e.target.value })} /></label><label>collection<input value={gold.collection} onChange={(e) => setGold({ ...gold, collection: e.target.value })} /></label><label>question<textarea value={gold.question} onChange={(e) => setGold({ ...gold, question: e.target.value })} /></label><label>expected_chunk_ids<textarea value={gold.expected_chunk_ids} onChange={(e) => setGold({ ...gold, expected_chunk_ids: e.target.value })} /></label><label>expected_paths<textarea value={gold.expected_paths} onChange={(e) => setGold({ ...gold, expected_paths: e.target.value })} /></label><label>expected_keywords<textarea value={gold.expected_keywords} onChange={(e) => setGold({ ...gold, expected_keywords: e.target.value })} /></label><label className="inline-check"><input type="checkbox" checked={gold.enabled} onChange={(e) => setGold({ ...gold, enabled: e.target.checked })} />enabled</label><button className="primary"><Save size={16} /> Save Gold Case</button><button type="button" onClick={useGold}>Use Gold Set in cases JSON</button></form><div className="rag-gold-list">{goldCases.map((item) => <article key={item.case_id} className="rag-gold-card"><strong>{item.case_id}</strong><p>{item.question}</p><button className="danger" onClick={() => deleteRagGoldCase(item.case_id).then(refreshGold)}><Trash2 size={15} /> Delete</button></article>)}{!goldCases.length ? <p className="empty-text">No saved RAG Gold Set cases yet.</p> : null}</div></div></div> : null}
  </section>;
}
function parse<T>(text: string, fallback: T): T { try { return JSON.parse(text) as T; } catch { return fallback; } }
function lines(text: string) { return text.split('\n').map((item) => item.trim()).filter(Boolean); }
function first(value: string) { return value.split('\n')[0]; }
function label(type: BenchmarkType) { return ({ mcp: 'MCP', llm: 'LLM', rag: 'RAG', workflow: 'Workflow', collaboration: 'Collaboration' } as Record<BenchmarkType, string>)[type]; }
function runName(type: BenchmarkType) { return `${label(type).toLowerCase()}-benchmark-${new Date().toISOString().slice(0, 10)}`; }
function defaultCases(type: BenchmarkType): BenchmarkCase[] { return type === 'rag' ? [{ case_id: 'rag-1', tool_name: 'rag.query', arguments: { collection: 'default', question: 'What is Jaycode?' }, enabled: true }] : [{ case_id: `${type}-1`, tool_name: 'filesystem.list', arguments: { path: '.' }, enabled: true }]; }
