import { BookOpen, Database, MessageSquare, RefreshCw, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { FieldHelp, PanelTitle } from '../components/DisplayPrimitives';
import type { LearningPlanRecord, MemoryRecord, RagDocument, RagResult, TaskSummary } from '../types';
import type { ChatMessage, ChatMode } from '../hooks/useKnowledgeChat';

type Props = { chatInput: string; chatMessages: ChatMessage[]; chatMode: ChatMode; chatSources: RagResult[]; knowledgeDocs: RagDocument[]; knowledgeNote: string; memories: MemoryRecord[]; learningPlans: LearningPlanRecord[]; latestTaskId: string; tasks: TaskSummary[]; selectedTaskId: string; onChatInputChange: (value: string) => void; onChatModeChange: (mode: ChatMode) => void; onKnowledgeNoteChange: (value: string) => void; onMemoryConfirm: (memoryId: string) => void; onMemoryDelete: (memoryId: string) => void; onMemoryReject: (memoryId: string) => void; onLearningPlanStatus: (planId: string, status: LearningPlanRecord['status']) => void; onOpenTask: (taskId: string) => void; onRefreshTasks: () => void; onSaveKnowledgeNote: () => void; onSend: () => void; };
export function ChatWorkspacePage({ chatInput, chatMessages, chatMode, chatSources, knowledgeDocs, knowledgeNote, memories, learningPlans, latestTaskId, tasks, selectedTaskId, onChatInputChange, onChatModeChange, onKnowledgeNoteChange, onMemoryConfirm, onMemoryDelete, onMemoryReject, onLearningPlanStatus, onOpenTask, onRefreshTasks, onSaveKnowledgeNote, onSend }: Props) {
  const candidates = memories.filter((item) => item.status === 'candidate').slice(0, 4); const confirmed = memories.filter((item) => item.status === 'confirmed').slice(0, 3);
  return <section className="page-grid chat-page">
    <div className="panel chat-sidebar"><PanelTitle icon={<MessageSquare size={17} />} title="追问上下文" action={<button className="icon-button" onClick={onRefreshTasks}><RefreshCw size={15} /></button>} /><div className="chat-mode-list">{([{ mode: 'task', label: '任务追问' }, { mode: 'knowledge', label: '知识库' }, { mode: 'coach', label: '学习陪练' }] as const).map((item) => <button key={item.mode} className={chatMode === item.mode ? 'active' : ''} onClick={() => onChatModeChange(item.mode)}>{item.label}</button>)}</div><div className="chat-current"><strong>当前任务</strong><p>{latestTaskId || '未选择任务'}</p></div><div className="memory-panel"><strong>Long-term memory</strong><p>{candidates.length} candidates / {confirmed.length} confirmed</p>{candidates.map((memory) => <article className="memory-candidate" key={memory.memory_id}><p>{memory.content}</p><div><button className="secondary" onClick={() => onMemoryConfirm(memory.memory_id)}>Confirm</button><button className="icon-button" title="Reject memory" onClick={() => onMemoryReject(memory.memory_id)}><X size={14} /></button></div></article>)}{confirmed.map((memory) => <div className="memory-confirmed" key={memory.memory_id}><span>{memory.content}</span><button className="icon-button" title="Delete memory" onClick={() => onMemoryDelete(memory.memory_id)}><Trash2 size={13} /></button></div>)}</div><div className="task-list">{tasks.slice(0, 10).map((task) => <button key={task.task_id} className={task.task_id === selectedTaskId ? 'active' : ''} onClick={() => onOpenTask(task.task_id)}><span>{task.goal}</span><small>{task.status}</small></button>)}</div></div>
    <div className="panel chat-main"><PanelTitle icon={<MessageSquare size={17} />} title="项目交互追问" /><div className="chat-messages">{chatMessages.map((message, index) => <div className={`chat-bubble ${message.role}`} key={`${message.role}-${index}`}><div className="markdown-view"><pre>{message.content}</pre></div></div>)}{!chatMessages.length ? <div className="chat-empty"><strong>开始追问项目</strong><p>选择任务和追问类型，然后询问项目结构、风险来源、知识库内容或学习路线。</p></div> : null}</div><div className="chat-composer"><textarea value={chatInput} onChange={(event) => onChatInputChange(event.target.value)} /><FieldHelp>任务追问结合当前任务；知识库模式检索 project-memory；陪练模式会继续追问。</FieldHelp><button className="primary" onClick={onSend}>发送追问</button></div></div>
    <div className="panel chat-sources"><PanelTitle icon={chatMode === 'coach' ? <BookOpen size={17} /> : <Database size={17} />} title={chatMode === 'task' ? '任务上下文' : chatMode === 'knowledge' ? '知识库内容' : '学习陪练计划'} /><div className="source-list">{chatMode === 'task' ? <div className="context-box"><strong>当前任务</strong><p>{latestTaskId || '未选择任务'}</p></div> : null}{chatMode === 'knowledge' ? <div className="knowledge-save-box"><strong>project-memory</strong><p>{knowledgeDocs.length} documents saved</p><textarea value={knowledgeNote} onChange={(event) => onKnowledgeNoteChange(event.target.value)} placeholder="保存人工判断、模块说明或复盘结论" /><button className="secondary" onClick={onSaveKnowledgeNote}>保存知识笔记</button></div> : null}{chatMode === 'coach' ? <LearningPlans plans={learningPlans} latestTaskId={latestTaskId} onStatus={onLearningPlanStatus} /> : chatSources.map((source) => <div className="source-item" key={`${source.chunk_id}-${source.path}`}><strong>{source.path ?? 'source'}</strong><small>{source.chunk_id}</small><p>{(source.content ?? '').split('\n')[0]}</p></div>)}{chatMode !== 'coach' && !chatSources.length ? <p className="empty-text">{chatMode === 'task' ? '任务追问后显示引用到的任务报告和知识线索。' : '知识库检索后显示 project-memory 命中的内容。'}</p> : null}</div></div>
  </section>;
}
function LearningPlans({ plans, latestTaskId, onStatus }: { plans: LearningPlanRecord[]; latestTaskId: string; onStatus: (planId: string, status: LearningPlanRecord['status']) => void }) { const [expanded, setExpanded] = useState(''); const ordered = [...plans].sort((a, b) => Number(b.task_id === latestTaskId) - Number(a.task_id === latestTaskId)).slice(0, 8); return <div className="learning-plan-box"><strong>学习计划</strong>{ordered.map((plan) => <div className="learning-plan-item" key={plan.plan_id}><div><span>{plan.topic}</span><small>{plan.status} · {plan.level} · {plan.plan.length} days</small></div><div className="learning-plan-actions"><button onClick={() => onStatus(plan.plan_id, plan.status === 'completed' ? 'active' : 'completed')}>{plan.status === 'completed' ? '继续' : '完成'}</button><button onClick={() => onStatus(plan.plan_id, 'paused')}>暂停</button><button onClick={() => setExpanded(expanded === plan.plan_id ? '' : plan.plan_id)}>{expanded === plan.plan_id ? '收起' : '详情'}</button></div>{expanded === plan.plan_id ? <pre>{plan.report_markdown}</pre> : null}</div>)}{!ordered.length ? <p className="empty-text">点击人工审核里的“学习任务”后，这里会保存学习计划。</p> : null}</div>; }
