import { Activity, BarChart3, FileText, RefreshCw, SlidersHorizontal } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { FieldHelp, KpiCard, PanelTitle } from '../components/DisplayPrimitives';
import type { LlmPromptAbTestResult, LlmPromptPayload, LlmPromptVersion, LlmTrace, LlmUsageDashboard } from '../types';

type Props = {
  prompts: LlmPromptVersion[]; usage: LlmUsageDashboard | null; traces: LlmTrace[];
  traceAgent: string; agentFilter: string;
  onAgentFilterChange: (value: string) => Promise<void>;
  onTraceAgentChange: (value: string) => Promise<void>;
  onActivatePrompt: (prompt: LlmPromptVersion) => Promise<void>;
  onSavePrompt: (payload: LlmPromptPayload) => Promise<void>;
  onRunAbTest: (payload: { agent: string; prompt_a: string; prompt_b: string; system_prompt: string; user_prompt: string; fallback: string }) => Promise<LlmPromptAbTestResult>;
  onRefresh: () => Promise<void>;
};

export function LlmPage({ prompts, usage, traces, traceAgent, agentFilter, onAgentFilterChange, onTraceAgentChange, onActivatePrompt, onSavePrompt, onRunAbTest, onRefresh }: Props) {
  const [editing, setEditing] = useState<LlmPromptVersion | null>(null);
  const [draft, setDraft] = useState<LlmPromptPayload>({ agent: 'planner', prompt_family: 'planner', prompt_version: 'planner.custom.v1', title: 'Custom planner prompt', description: '', system_suffix: '', is_active: false });
  const [ab, setAb] = useState({ agent: 'planner', prompt_a: 'planner.v1', prompt_b: 'planner.v2', system_prompt: '你是 Jaycode 的 Prompt A/B 测试执行器。请输出结构清晰、可验证、可行动的中文回答。', user_prompt: '请分析一个 FastAPI + LangGraph 项目的风险，并给出治理建议。', fallback: 'LLM 未配置或调用失败，返回 fallback。' });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [result, setResult] = useState<LlmPromptAbTestResult | null>(null);
  const agents = ['', ...Array.from(new Set(prompts.map((item) => item.agent))).sort()];
  const activePrompts = prompts.filter((item) => item.agent === ab.agent); const total = usage?.total;
  const edit = (prompt?: LlmPromptVersion) => { const value = prompt ?? null; setEditing(value); setDraft(value ? { agent: value.agent, prompt_family: value.prompt_family, prompt_version: value.prompt_version, title: value.title, description: value.description ?? '', system_suffix: value.system_suffix ?? '', is_active: value.is_active } : { agent: agentFilter || 'planner', prompt_family: agentFilter || 'planner', prompt_version: `${agentFilter || 'planner'}.custom.v1`, title: 'Custom prompt', description: '', system_suffix: '', is_active: false }); setMessage(''); };
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { await onSavePrompt(draft); setMessage(editing ? 'Prompt 已更新。' : 'Prompt 已创建。'); setEditing(null); } catch (error) { setMessage(error instanceof Error ? error.message : 'Prompt 保存失败'); } finally { setBusy(false); } }
  async function runAb(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { setResult(await onRunAbTest(ab)); } catch (error) { setMessage(error instanceof Error ? error.message : 'A/B Test 运行失败'); } finally { setBusy(false); } }
  return <section className="page-grid llm-page">
    <div className="panel llm-console-panel"><PanelTitle icon={<SlidersHorizontal size={17} />} title="LLM 控制台" action={<button className="icon-button" onClick={() => onRefresh()}><RefreshCw size={15} /></button>} /><div className="llm-console-body"><div className="llm-filter"><label><span>Agent</span><select value={agentFilter} onChange={(e) => onAgentFilterChange(e.target.value)}>{agents.map((agent) => <option key={agent || 'all'} value={agent}>{agent || 'all agents'}</option>)}</select></label><FieldHelp>筛选会影响 Token/Cost 看板和 Trace 统计范围。</FieldHelp></div><div className="llm-kpi-stack"><KpiCard label="calls" value={String(total?.calls ?? 0)} /><KpiCard label="tokens" value={number(total?.total_tokens ?? 0)} /><KpiCard label="cost" value={`$${cost(total?.estimated_cost_usd ?? 0)}`} /><KpiCard label="fallback" value={`${Math.round((total?.fallback_rate ?? 0) * 100)}%`} /></div><div className="llm-note"><strong>cost basis</strong><p>{usage?.cost_basis ?? '等待 LLM Trace 生成后显示统计。'}</p></div></div></div>
    <div className="panel llm-dashboard"><PanelTitle icon={<BarChart3 size={17} />} title="Token / Cost 看板" />{usage ? <div className="usage-sections"><Usage title="By Agent" items={usage.by_agent} /><Usage title="By Model" items={usage.by_model} /><Usage title="By Prompt" items={usage.by_prompt} /></div> : <p className="empty-text">暂无 usage 数据。</p>}</div>
    <div className="panel llm-trace-section"><PanelTitle icon={<Activity size={17} />} title="LLM Trace" action={<button className="icon-button" onClick={() => onRefresh()}><RefreshCw size={15} /></button>} /><div className="trace-toolbar"><label><span>Agent</span><select value={traceAgent} onChange={(e) => onTraceAgentChange(e.target.value)}>{agents.map((agent) => <option key={agent || 'all'} value={agent}>{agent || 'all agents'}</option>)}</select></label></div><div className="trace-list">{traces.map((trace) => <Trace key={trace.trace_id} trace={trace} />)}{!traces.length ? <p className="empty-text">暂无 LLM 调用记录。</p> : null}</div></div>
    <div className="panel llm-prompts"><PanelTitle icon={<SlidersHorizontal size={17} />} title="Prompt 版本管理" action={<button className="secondary" onClick={() => edit()}>新建</button>} /><div className="prompt-list">{prompts.filter((item) => !agentFilter || item.agent === agentFilter).map((prompt) => <article key={`${prompt.agent}-${prompt.prompt_version}`} className={`prompt-card ${prompt.is_active ? 'active' : ''}`}><header><div><strong>{prompt.prompt_version}</strong><span>{prompt.agent} / {prompt.prompt_family}</span></div><button className="secondary" disabled={prompt.is_active || busy} onClick={() => onActivatePrompt(prompt).catch((error) => setMessage(error instanceof Error ? error.message : 'Prompt 激活失败'))}>{prompt.is_active ? 'active' : '设为 active'}</button><button className="secondary" onClick={() => edit(prompt)}>编辑</button></header><p>{prompt.description || prompt.title}</p></article>)}{!prompts.length ? <p className="empty-text">暂无 Prompt 版本。</p> : null}</div>
      <div className="prompt-lab"><form className="prompt-editor" onSubmit={save}><PanelTitle icon={<FileText size={17} />} title={editing ? '编辑 Prompt' : '新增 Prompt'} /><label>Agent<input value={draft.agent} onChange={(e) => setDraft({ ...draft, agent: e.target.value })} /></label><label>Family<input value={draft.prompt_family ?? ''} onChange={(e) => setDraft({ ...draft, prompt_family: e.target.value })} /></label><label>Version<input value={draft.prompt_version} onChange={(e) => setDraft({ ...draft, prompt_version: e.target.value })} /></label><label>Title<input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label><label>Description<input value={draft.description ?? ''} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><label>System suffix<textarea value={draft.system_suffix ?? ''} onChange={(e) => setDraft({ ...draft, system_suffix: e.target.value })} /></label><label className="toggle-row"><input type="checkbox" checked={Boolean(draft.is_active)} onChange={(e) => setDraft({ ...draft, is_active: e.target.checked })} />保存后设为 active</label><button className="primary" disabled={busy}>{busy ? '保存中...' : '保存 Prompt'}</button></form>
      <form className="prompt-abtest" onSubmit={runAb}><PanelTitle icon={<Activity size={17} />} title="Prompt A/B Test" /><label>Agent<select value={ab.agent} onChange={(e) => setAb({ ...ab, agent: e.target.value })}>{agents.filter(Boolean).map((agent) => <option key={agent}>{agent}</option>)}</select></label><label>Prompt A<select value={ab.prompt_a} onChange={(e) => setAb({ ...ab, prompt_a: e.target.value })}>{activePrompts.map((p) => <option key={p.prompt_version}>{p.prompt_version}</option>)}</select></label><label>Prompt B<select value={ab.prompt_b} onChange={(e) => setAb({ ...ab, prompt_b: e.target.value })}>{activePrompts.map((p) => <option key={p.prompt_version}>{p.prompt_version}</option>)}</select></label><label>System prompt<textarea value={ab.system_prompt} onChange={(e) => setAb({ ...ab, system_prompt: e.target.value })} /></label><label>Test input<textarea value={ab.user_prompt} onChange={(e) => setAb({ ...ab, user_prompt: e.target.value })} /></label><label>Fallback<input value={ab.fallback} onChange={(e) => setAb({ ...ab, fallback: e.target.value })} /></label><button className="primary" disabled={busy || !ab.prompt_a || !ab.prompt_b}>{busy ? '对比中...' : '运行 A/B Test'}</button>{result ? <pre className="mcp-result">{JSON.stringify(result, null, 2)}</pre> : null}</form></div>{message ? <p className="prompt-message">{message}</p> : null}</div>
  </section>;
}
function Usage({ title, items }: { title: string; items: LlmUsageDashboard['by_agent'] }) { return <section className="usage-table-section"><h3>{title}</h3>{items.map((item) => <div className="usage-row" key={`${title}-${item.name}`}><span>{item.name}</span><span>{item.calls}</span><span>{number(item.total_tokens)}</span><span>{item.avg_latency_ms}ms</span><span>{Math.round(item.fallback_rate * 100)}%</span><span>${cost(item.estimated_cost_usd)}</span></div>)}</section>; }
function Trace({ trace }: { trace: LlmTrace }) { return <details className={`trace-item ${trace.fallback_used ? 'fallback' : 'llm'}`}><summary><span className="trace-agent">{trace.agent}</span><span>{trace.model || 'no model'}</span><span>{trace.prompt_version}</span><span>{trace.latency_ms}ms</span></summary><div className="trace-body"><p>trace_id: {trace.trace_id}</p>{trace.error_message ? <p className="error-text">{trace.error_message}</p> : null}<pre>{trace.output_text || ''}</pre></div></details>; }
const number = (value: number) => new Intl.NumberFormat('en-US').format(value);
const cost = (value: number) => value.toFixed(value > 0 && value < 0.01 ? 6 : 4);
