import { Activity, Play, RefreshCw } from 'lucide-react';
import { FormEvent } from 'react';
import { PanelTitle } from '../components/DisplayPrimitives';
import { ApiErrorNotice } from '../components/ApiErrorNotice';
import { TaskTimeline } from '../components/TaskTimeline';
import { EventDetail, ResumePanel, ReviewBox, RunOutputs } from '../components/run/RunDetails';
import type { AgentEvent, ResumeSnapshot } from '../types';

type Props = { goal: string; projectPath: string; maxFiles: number; requireReview: boolean; running: boolean; submitLabel: string; error: unknown; events: AgentEvent[]; latestTaskId: string; latestStatus: string; workflowName: string; taskNeedsReview: boolean; reviewComment: string; resumeSnapshots: ResumeSnapshot[]; selectedEvent: AgentEvent | null; toolCalls: string[]; agentOutputs: string[]; onReviewCommentChange: (value: string) => void; onReview: (action: 'approve' | 'reject' | 'revise') => void; onReviewAction: (action: string, payload?: Record<string, unknown>) => void; onGoalChange: (value: string) => void; onProjectPathChange: (value: string) => void; onMaxFilesChange: (value: number) => void; onRequireReviewChange: (value: boolean) => void; onSubmit: (event: FormEvent) => void; };
export function RunPage({ goal, projectPath, maxFiles, requireReview, running, submitLabel, error, events, latestTaskId, latestStatus, workflowName, taskNeedsReview, reviewComment, resumeSnapshots, selectedEvent, toolCalls, agentOutputs, onReviewCommentChange, onReview, onReviewAction, onGoalChange, onProjectPathChange, onMaxFilesChange, onRequireReviewChange, onSubmit }: Props) {
  return <section className="page-grid run-page"><div className="panel run-panel"><PanelTitle icon={<Play size={17} />} title="任务入口" /><div className="start-guide"><strong>先做这三步</strong><ol><li>填目标和项目路径</li><li>选运行模式</li><li>点击开始执行</li></ol></div><form className="run-form" onSubmit={onSubmit}><label>目标<textarea value={goal} onChange={(event) => onGoalChange(event.target.value)} /></label><label>项目路径<input value={projectPath} onChange={(event) => onProjectPathChange(event.target.value)} /></label><label>最大文件数<input type="number" min={1} value={maxFiles} onChange={(event) => onMaxFilesChange(Number(event.target.value))} /></label><label className="toggle-row"><input type="checkbox" checked={requireReview} onChange={(event) => onRequireReviewChange(event.target.checked)} />人工审核</label><button className="primary" disabled={running}>{running ? <RefreshCw className="spin" size={17} /> : <Play size={17} />}{running ? '执行中...' : submitLabel}</button></form><ApiErrorNotice error={error} /></div><div className="panel timeline-large"><PanelTitle icon={<Activity size={17} />} title="执行过程" /><TaskTimeline events={events} /></div><div className="panel state-panel"><PanelTitle icon={<Activity size={17} />} title="结果总览" /><dl className="state-summary"><dt>Task</dt><dd>{latestTaskId || '未运行'}</dd><dt>Status</dt><dd>{latestStatus}</dd><dt>Workflow</dt><dd>{workflowName}</dd></dl>{taskNeedsReview ? <ReviewBox comment={reviewComment} onCommentChange={onReviewCommentChange} onReview={onReview} onReviewAction={onReviewAction} /> : null}<ResumePanel snapshots={resumeSnapshots} events={events} /><EventDetail event={selectedEvent} /><RunOutputs toolCalls={toolCalls} agentOutputs={agentOutputs} /></div></section>;
}
